#!/bin/bash
#Run on clean install of raspbian jessie lite to setup host parameters, IP settings and Java Configs

#get java
sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get -y install oracle-java8-jdk
sudo apt-get -y install jython

#updates host and IP params
cd /etc
sudo sed -i -e 's/raspberrypi/p45-pi-01/g' hostname
sudo sed -i -e 's/raspberrypi/p45-pi-01/g' hosts
sudo sed -i -e 's/127.0.1.1/172.23.253.56/g' hosts

#reboots to ensure changes are implemented
echo "REBOOTING"
sudo reboot