#!/bin/bash

#Ensures root
[ `whoami` = root ] || exec sudo su -c $0 root

#get java & other software dependencies
apt-get update &&  apt-get -y upgrade
apt-get -y install oracle-java8-jdk
apt-get -y install jython
apt-get -y install python-picamera
apt-get -y install i2c-tools

#Gets Pi4J, WiringPi - used for GPIO communications and JRPiCam - the Java Raspberry Pi Camera Interface
cd ../..
git clone https://github.com/bseeley/JRPiCam.git
git clone git://git.drogon.net/wiringPi
cd wiringPi/
./build
cd ..
curl -s get.pi4j.com | sudo bash

#set JAVA_HOME to the path of the new java install as apt-get apparently doesn't do this
echo "export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt" >> /etc/bash.bashrc
echo "export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt" >> /root/.bashrc

echo 'export JYTHONPATH="/opt/pi4j/lib/pi4j-core.jar:/opt/pi4j/lib/pi4j-device.jar:/opt/pi4j/lib/pi4j-gpio-extension.jar:/opt/pi4j/lib/pi4j-service.jar:/usr/share/jython/Lib:/home/pi/JRPiCam/JRPiCam-v1.0.1.jar"'  >> /etc/bash.bashrc
echo 'export JYTHONPATH="/opt/pi4j/lib/pi4j-core.jar:/opt/pi4j/lib/pi4j-device.jar:/opt/pi4j/lib/pi4j-gpio-extension.jar:/opt/pi4j/lib/pi4j-service.jar:/usr/share/jython/Lib:/home/pi/JRPiCam/JRPiCam-v1.0.1.jar"'  >> /root/.bashrc

echo "CHANGES MADE TO CONFIGS, REBOOTING"
sudo reboot