#!/bin/bash

[ `whoami` = root ] || exec sudo su -c $0 root

#set JAVA_HOME to the path of the new java install
echo "export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt" >> /etc/bash.bashrc
echo "export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt" >> /root/.bashrc

echo 'export JYTHONPATH="/opt/pi4j/lib/pi4j-core.jar:/opt/pi4j/lib/pi4j-device.jar:/opt/pi4j/lib/pi4j-gpio-extension.jar:/opt/pi4j/lib/pi4j-service.jar:/usr/share/jython/Lib"'  >> /etc/bash.bashrc
echo 'export JYTHONPATH="/opt/pi4j/lib/pi4j-core.jar:/opt/pi4j/lib/pi4j-device.jar:/opt/pi4j/lib/pi4j-gpio-extension.jar:/opt/pi4j/lib/pi4j-service.jar:/usr/share/jython/Lib"'  >> /root/.bashrc

echo 'alias temp="/opt/vc/bin/vcgencmd measure_temp"'  >> /etc/bash.bashrc
echo 'alias temp="/opt/vc/bin/vcgencmd measure_temp"'  >> /root/.bashrc

echo 'dtparam=i2c_arm=on'>>/boot/config.txt

echo "CHANGES MADE TO CONFIGS, REBOOTING"
sudo reboot