#!/bin/bash
#Starts GDA server

#Finds Directory of Script
DIR="$(dirname "$(readlink -f "$0")")"

#Runs the launcher
java -jar $DIR/../../plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -c $DIR/..